name: simple
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.15
  overlay_support: ^2.1.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  provider: ^6.0.5
  path_provider: ^2.1.3
  dio: ^5.1.1
  smooth_page_indicator: ^1.1.0
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.2.5
  flutter_inappwebview: ^6.0.0 # or latest stable


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.jpg
    - assets/image/logo1.png
    - assets/image/carousel1.jpg
    - assets/image/carousel2.jpg
    - assets/image/carousel3.jpg
    - assets/image/dental.jpeg
    - assets/image/healthServicesImage.jpg
    - assets/image/drPaulRaj.jpg
    - assets/image/drBalaKrishnan.jpg
    - assets/image/drJenarthan.jpg
    - assets/image/newsEvent1.png
    - assets/image/newsEvent2.png
    - assets/image/awarenessimage.jpg

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700


